### ISSUE TITLE
please generate pdf with bookmark

### ISSUE THREAD

**Issue by itviewer** [richelbilderbeek/BoostGraphTutorial#46]
please generate pdf with bookmark

**Comment by richelbilderbeek** [comment]
Great idea! Do you know how? If no, it will not be done as fast as you'd like.

**Comment by itviewer** [comment]
I think this can help https://wiki.lyx.org/FAQ/PDF#bookmarks

**Comment by richelbilderbeek** [comment]
Thanks for the Googling. Will do so when it is at the top of my priority list!

**Comment by richelbilderbeek** [comment]
Check it out, tried for an hour, no success. Would be great if someone else would give it a shot. Else, I estimate that I will do so around June (after another 5 months).

**Comment by richelbilderbeek** [comment]
Note to self:

Just click here:

![2018-01-12-100724_872x536_scrot](https://user-images.githubusercontent.com/2098230/34867435-692468a8-f780-11e7-878b-996e86c135c4.png)

Convert like this:

```
lyx --export pdflatex boost_graph_tutorial.lyx -E pdf boost_graph_tutorial.pdf
```

Tutorial has an overview and clickable TOC:

![2018-01-12-100805_1920x1080_scrot](https://user-images.githubusercontent.com/2098230/34867479-807bf0fc-f780-11e7-8749-227c7d6dd31c.png)

**Comment by richelbilderbeek** [comment]
@itviewer: fixed it, hope you like it.
