### ISSUE TITLE
optimize travis ci

### ISSUE THREAD

**Issue by mywtfmp3** [richelbilderbeek/BoostGraphTutorial#50]
I am not familiar how CI works. Please bear with my ignorance.

When I just push request a typo fix brach, the CI need to apt install a huge amount of packages `g++ textlive` etc before building this tutorial. It really takes a huge amount of time to simply install packges. I feel my typo-fix pull request is simply wasting CI resources.

Is CI build machine ephemeral? Or can we custmoze it so that it install all the necessary packages beforehand. If it's not possible, can we use customized docker images to do it?

Thanks ahead.

**Comment by mywtfmp3** [comment]
Perhaps it's better to let admin to decide whether or not to start a build. For example, some repo requires a admin to post "ok to test" to start CI.

**Comment by richelbilderbeek** [comment]
Hi @mywtfmp3, thanks for thinking along! I think you don't know this yet, that would your commit be `fix a typo [skip ci]`, Travis would not be started. Happy to teach you this trick :+1:
