### ISSUE TITLE
Count the number of levels in an undirected graph

### ISSUE THREAD

**Issue by mywtfmp3** [richelbilderbeek/BoostGraphTutorial#55]
Algorithm 53 - "Count the number of levels in an undirected graph", take a single parameter `graph`.

What does number of levels of a graph mean in the tutorial? The only definition I can find is https://en.wikipedia.org/wiki/Level_structure.

However, the definition on wiki takes a graph and a root vertex.

**Comment by richelbilderbeek** [comment]
Great feedback, thanks!

I assume the algorithm either uses the first vertex as a root vertex, or counts the maximum distance without self-loops possible.

As I think this is too much hand-waving, I will check this on Saturday.

**Comment by richelbilderbeek** [comment]
Feel ill, will postpone to tomorrow.

**Comment by mywtfmp3** [comment]
@richelbilderbeek take care. It's no hurry. There's no project leader after us.

**Comment by richelbilderbeek** [comment]
I checked. What it does: from a starting vertex, it looks how many levels of neighbouring vertices there are.

 * Level 0: the initial vertex
 * Level 1: the neightbours of level 0
 * Level 2: the neightbours of level 1
 * etc...

```
template <typename graph>
int count_ undirected_graph_levels(
typename boost::graph_traits<graph>::vertex_descriptor
vd,
const graph& g
) noexcept
```

I will improve the wording in the documentation.

**Comment by mywtfmp3** [comment]
This problem can be solved with `breadth_first_search` algorithm in boost graph library. The algorithm has a connvinience template function `record_distance`, that can record distances of all vertices connected to the root.

```cpp
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/breadth_first_search.hpp>
#include <unordered_map>

template <typename graph>
int count_undirected_graph_levels(
  typename boost::graph_traits<graph>::vertex_descriptor vd, 
  const graph& g) noexcept
{
  using vertex_descriptor = typename boost::graph_traits<graph>::vertex_descriptor;

  std::unordered_map<vertex_descriptor, vertex_descriptor> distance;
  auto distance_map = boost::make_assoc_property_map(distance);

  boost::breadth_first_search(g, vd, 
    boost::visitor(boost::make_bfs_visitor(
      boost::record_distances(distance_map, boost::on_tree_edge()))));

  typename boost::graph_traits<graph>::vertices_size_type level = 0;
  for (const auto p : distance)
    level = std::max(level, p.second);

  return level;
}
```

**Comment by mywtfmp3** [comment]
If using `breadth_first_search` instead, we can convey more information than number of levels. It can return level structure as in [wikipedia](https://en.wikipedia.org/wiki/Level_structure), showing which vertex belongs to which level. Shall we change the signature of this function to return more information?

**Comment by mywtfmp3** [comment]
I wasn't clear. I am thinking of creating a new function like `collection_vertex_depths` and use this function to return number of levels.

**Comment by mywtfmp3** [comment]
BTW, how do you organize the code in your git repo? From what I see,

`*.h` has nothing exept function sigature, `*.impl` contains actually implementation.

**Comment by richelbilderbeek** [comment]
> I wasn't clear. I am thinking of creating a new function like collection_vertex_depths 
> and use this function to return number of levels.
Sounds brilliant!

**Comment by richelbilderbeek** [comment]
> BTW, how do you organize the code in your git repo? From what I see,
>
> *.h has nothing exept function sigature, *.impl contains actually implementation.

This is documented in [CONTRIBUTING.md](https://github.com/richelbilderbeek/BoostGraphTutorial/blob/master/CONTRIBUTING.md). In short: the code in `.impl` is shown in the tutorial. This makes the code displayed as clean as possible.

**Comment by mywtfmp3** [comment]
Thanks for ur clarification. I wasn't too sure because I saw some `*.h` file didn't include `*.impl` file. Here is `create_empty_directed_graph.h` in the tutorial. I am surprised it hasn't generated a compiler error. Perhaps it needs a include directive here?


```cpp
#ifndef CREATE_EMPTY_DIRECTED_GRAPH_H
#define CREATE_EMPTY_DIRECTED_GRAPH_H

#include <boost/graph/adjacency_list.hpp>

boost::adjacency_list<> create_empty_directed_graph() noexcept;

#endif // CREATE_EMPTY_DIRECTED_GRAPH_H
```

**Comment by richelbilderbeek** [comment]
That header files looks fine. I like to do a forward declaration whenever possible. In this case, as all types are known, it can be done. This speeds up compile times.
