### ISSUE TITLE
Mention @mywtfmp3 in acknowledgements

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/BoostGraphTutorial#59]
@mywtfmp3 has made multiple improvements to my code and should be added in the acknowledgements section.

@mywtfmp3:

  * 1) agree?
  * 2) iff yes, what is your complete name?

Thanks for your help :+1:

**Comment by mywtfmp3** [comment]
I am flattered. My full name is `John Zhang Zongren`.

I am feeling embarrassed to see my name as contributors at the momemt, as I have done little. Let me finish reading the tutorial for the first round, making changes and commits in the meantime. By that time, I will be happy to be listed here.

So let's close this and hopefully reopen this sometime not too far in future?

**Comment by richelbilderbeek** [comment]
If you insist: sure!
