### ISSUE TITLE
Syntax highlighting for C++ code in lyx

### ISSUE THREAD

**Issue by mywtfmp3** [richelbilderbeek/BoostGraphTutorial#62]
Any interest in doing it? I don't know how to do it exactly, but it seems possible,

https://stackoverflow.com/questions/2116944/insert-programming-code-in-a-lyx-document

Just realized that .lyx file can be opened by lyx program. I was editing it with vim all the time.

**Comment by richelbilderbeek** [comment]
Well, that is exactly what I am doing already :grin:

**Comment by mywtfmp3** [comment]
Great. I am closing this.
